[workspace]
authors = ["Maulik Madhavi <maulikmadhavi@gmail.com>"]
channels = ["conda-forge"]
name = "streamlit"
platforms = ["win-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.13.5,<3.14"
pip = ">=25.1.1,<26"


[pypi-dependencies]
streamlit = ">=1.47.0, <2"
numpy = ">=2.3.1, <3"
pandas = ">=2.3.1, <3"
matplotlib = ">=3.10.3, <4"
plotly = ">=6.2.0, <7"
opencv-python = ">=4.11.0.86, <5"
streamlit-image-comparison = ">=0.0.4, <0.0.5"
streamlit-webrtc = ">=0.64.5, <0.65"
